#!/bin/bash

# DO NOT CHANGE THE QUEUE! YOU **MUST** ONLY USE THE QUEUE: short_serial
#BSUB -q airoldi

# EDIT THE EMAIL-ADDRESS BELOW TO YOUR FAS EMAIL:
#BSUB -u jbischof@fas.harvard.edu

# THE JOB ARRAY:
#BSUB -J "process_data_master_script"

# THE COMMAND TO GIVE TO R, CHANGE TO THE APPROPRIATE FILENAME:
cutoff=500
python process_data_master_script.py /n/airoldifs1/jbischof/reuters_output/ /n/airoldifs1/jbischof/reuters_output/mmm_raw_data/ ${cutoff}


