#!/bin/bash

# DO NOT CHANGE THE QUEUE! YOU **MUST** ONLY USE THE QUEUE: short_serial
#BSUB -q airoldi

# EDIT THE EMAIL-ADDRESS BELOW TO YOUR FAS EMAIL:
#BSUB -u jbischof@fas.harvard.edu

# THE JOB ARRAY:
#BSUB -J "get_reuters_doc_topic_membs[1-10]"

main_dir=/n/airoldifs1/jbischof/reuters_output/mmm_folds/fold${LSB_JOBINDEX}/

# THE COMMAND TO GIVE TO R, CHANGE TO THE APPROPRIATE FILENAME:
python ../mmm_class_functions/process_get_reuters_doc_topic_membs.py $main_dir
