#!/bin/bash

# QUEUE
#BSUB -q normal_serial

# EDIT THE EMAIL-ADDRESS BELOW TO YOUR FAS EMAIL:
#BSUB -u jbischof@fas.harvard.edu

# THE JOB ARRAY:
#BSUB -J "translate_lda_data"

main_dir=/n/airoldifs1/jbischof/reuters_output/
raw_data_dir=${main_dir}mmm_raw_data/
out_dir=${raw_data_dir}ldac_data/
cutoff=500

# Create output directory if doesn't already exist
if [ ! -d $out_dir ]
then
   mkdir $out_dir
fi

python ../mmm_class_functions/translate_data_for_ldac.py ${main_dir} ${cutoff}
