#!/bin/bash

# QUEUE
#BSUB -q normal_serial

# EDIT THE EMAIL-ADDRESS BELOW TO YOUR FAS EMAIL:
#BSUB -u jbischof@fas.harvard.edu

# THE JOB ARRAY:
#BSUB -J "get_svm_liblinear_train[1-10]"

# THE COMMAND TO GIVE TO R, CHANGE TO THE APPROPRIATE FILENAME:
main_dir=/n/airoldifs1/jbischof/reuters_output/mmm_folds/fold${LSB_JOBINDEX}/
cutoff=250
python ../mmm_class_functions/liblinear_train.py $main_dir $cutoff svm