#!/bin/bash

# DO NOT CHANGE THE QUEUE! YOU **MUST** ONLY USE THE QUEUE: short_serial
#BSUB -q airoldi

# EDIT THE EMAIL-ADDRESS BELOW TO YOUR FAS EMAIL:
#BSUB -u jbischof@fas.harvard.edu

# THE JOB ARRAY:
#BSUB -J "process_model_comp_liblinear_svm"

# THE COMMAND TO GIVE TO R, CHANGE TO THE APPROPRIATE FILENAME:
main_dir=/n/airoldifs1/jbischof/reuters_output/
cutoff=500
./process_model_comp_liblinear.sh $main_dir $cutoff svm
